name: sarif-to-annotations
description: Convert .SARIF files (produces by PMD, ESLint and other static analyzers) to GitHub Annotations
inputs:
  fileName:
    description: .SARIF report file name
    required: true
  annotateOnlyChangedFiles:
    description: >-
      Annotate all files mentioned in the SARIF report, or only files that have changed.
      All files will be annotated if set to FALSE (default). Only modified files will be annotated if TRUE.
    required: false
    default: 'false'
  changedFiles:
    description: >-
      List of files that have been changed. Files must be separated by spaces.
      Required if annotateOnlyChangedFiles == true.
      E.g.: '/src/index.js /src/helper.js /src/constant/index.js'
    required: false
    default: ''
outputs:
  status:
    description: Action exit status
  violation_error_number:
    description: Number of Errors in the report. Include only number of errors in changed files if annotateOnlyChangedFiles == true.
  violation_warning_number:
    description: Number of Warnings in the report. Include only number of warnings in changed files if annotateOnlyChangedFiles == true.
  violation_notice_number:
    description: Number of Notices in the report. Include only number of notices in changed files if annotateOnlyChangedFiles == true.
  violation_total_number:
    description: Total number of violations in the report. Include only number of violations in changed files if annotateOnlyChangedFiles == true.
runs:
  using: node16
  main: dist/index.js
branding:
  icon: code
  color: red
